### ISSUE TITLE
Check json-ld context for camel case properties

### ISSUE THREAD

**Issue by azaroth42** [linked-art/linked.art#506]
and other errors

**Comment by bluebinary** [comment]
Here are the current keys that have camel-cased properties:

```
 - subState
 - subState_of
 - hasTopConcept
 - topConceptOf
 - inScheme
```

Found via the following Python script:

```
#!/usr/bin/python3

import json
import re

context = "/path/to/linked-art.json"

with open(context, "r") as handle:
	if data := json.load(handle):
		data = data["@context"]
		
		for key in data:
			if re.match(r"[a-z]{1,}[A-Z]{1}", key):  # check if an upper-case character follows some lower case
				print(" - %s" % (key))
			
```

There may be some other property names that fall outside the pattern, but these were the ones that caught initial attention.

**Comment by azaroth42** [comment]
Fixed :)

**Comment by bluebinary** [comment]
I noticed that `subState` and `subState_of` are still present in the latest version of the published Linked.Art context: `https://linked.art/ns/v1/linked-art.json`

Are these two properties needed for the 1.0 release, if not could we propose to remove them, or at least to rename them to `sub_state` and `sub_state_of` for consistency with the naming convention used for all of the other properties, or is renaming these two properties impossible due to some pre-existing use that would be too complex to change?

**Comment by bluebinary** [comment]
Separately I noticed that `hasTopConcept`, `topConceptOf` and `inScheme` have been completely removed from the Linked.Art context document rather than being renamed; there are no remaining references to the underlaying schema properties that they mapped to, which were: `skos:hasTopConcept`, `skos:topConceptOf` and `skos:inScheme` respectively.

As I'm not sure that their removal was explicitly documented elsewhere, I just wanted to note it here for future reference.

**Comment by azaroth42** [comment]
Recipe for concept usage, and discussion about extensions for extra-CRM details

**Comment by azaroth42** [comment]
Concepts documented now in model: https://linked.art/model/concept/
sub_state properties renamed and fixed in context
